# Generated by Django 3.2.9 on 2021-12-27 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import random


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('iban', models.CharField(max_length=28, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=6, max_digits=21)),
                ('balance_freeze', models.DecimalField(decimal_places=6, default=0, max_digits=21)),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('other_iban', models.CharField(max_length=34)),
                ('info_label', models.CharField(default='Note', max_length=30)),
                ('commission_percent', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_iban', models.CharField(max_length=34)),
                ('receiver_iban', models.CharField(max_length=34)),
                ('sender_card_number', models.BigIntegerField(null=True)),
                ('receiver_card_number', models.BigIntegerField(null=True)),
                ('value', models.DecimalField(decimal_places=6, max_digits=21)),
                ('commission', models.DecimalField(decimal_places=6, default=0, max_digits=21)),
                ('info', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.currencies')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.templates')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_buy', models.BigIntegerField()),
                ('course_sale', models.BigIntegerField()),
                ('change_time', models.TimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.currencies')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cardholder_name', models.CharField(max_length=30)),
                ('expiration_date', models.DateField()),
                ('security_code', models.IntegerField(default=functools.partial(random.Random.randint, *(1, 999), **{}))),
                ('is_freeze', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.accounts')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.clients')),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='clients',
            field=models.ManyToManyField(to='mainapp.Clients'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.currencies'),
        ),
    ]
