# Generated by Django 3.2.9 on 2021-11-21 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('fullname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('value', models.DecimalField(decimal_places=6, max_digits=21)),
                ('commission', models.DecimalField(decimal_places=6, max_digits=21)),
                ('is_active', models.BooleanField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.currencies')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='mainapp.clients')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='mainapp.clients')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.templates')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_buy', models.BigIntegerField()),
                ('course_sale', models.BigIntegerField()),
                ('change_time', models.TimeField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.currencies')),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cardholder_name', models.CharField(max_length=30)),
                ('expiration_date', models.DateField()),
                ('security_code', models.IntegerField()),
                ('cardholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=6, max_digits=21)),
                ('clients', models.ManyToManyField(related_name='clients', to='mainapp.Clients')),
            ],
        ),
    ]
