# Generated by Django 3.2.9 on 2021-12-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='other_iban',
            field=models.CharField(max_length=34, null=True),
        ),
    ]
