# Generated by Django 3.2.9 on 2021-11-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.currencies'),
        ),
    ]
