# Generated by Django 3.2.9 on 2021-11-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='cardholder',
            new_name='client',
        ),
    ]
