# Generated by Django 3.2.9 on 2021-12-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='is_freeze',
            field=models.BooleanField(default=0),
        ),
    ]
