# Generated by Django 3.2.9 on 2021-12-23 08:54

from django.db import migrations, models
import functools
import random


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211223_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='security_code',
            field=models.IntegerField(default=functools.partial(random.Random.randint, *(1, 999), **{})),
        ),
        migrations.AlterField(
            model_name='courses',
            name='change_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
