# Generated by Django 3.2.9 on 2021-12-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_templates_other_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='note',
            field=models.CharField(default='', max_length=50),
        ),
    ]
