# Generated by Django 3.2.9 on 2021-12-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_cards_is_freeze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='balance_freeze',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=21),
        ),
    ]
