# Generated by Django 3.2.9 on 2021-12-20 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_transactions_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='templates',
            name='is_send',
        ),
        migrations.AddField(
            model_name='templates',
            name='is_need_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templates',
            name='is_need_iban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templates',
            name='label',
            field=models.CharField(default='Note', max_length=30),
        ),
        migrations.AddField(
            model_name='templates',
            name='note_type',
            field=models.TextField(default='text'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='receiver_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_card', to='mainapp.cards'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sender_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_card', to='mainapp.cards'),
        ),
    ]
