# Generated by Django 3.2.9 on 2021-12-25 11:03

from django.db import migrations, models
import functools
import random


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211223_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templates',
            name='commission_percent',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='transactions',
            name='receiver_card_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sender_card_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='security_code',
            field=models.IntegerField(default=functools.partial(random.Random.randint, *(1, 999), **{})),
        ),
    ]
