# Generated by Django 3.2.9 on 2021-12-22 19:12

from django.db import migrations, models
import functools
import random


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_cards_security_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='security_code',
            field=models.IntegerField(default=functools.partial(random.Random.randint, *(1, 999), **{})),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='commission',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=21),
        ),
    ]
