# Generated by Django 3.2.9 on 2021-12-25 11:23

from django.db import migrations, models
import django.db.models.deletion
import functools
import random


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211225_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='security_code',
            field=models.IntegerField(default=functools.partial(random.Random.randint, *(1, 999), **{})),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.templates'),
        ),
    ]
