# Generated by Django 3.2.9 on 2021-12-25 12:01

from django.db import migrations, models
import functools
import random


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211225_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='security_code',
            field=models.IntegerField(default=functools.partial(random.Random.randint, *(1, 999), **{})),
        ),
        migrations.AlterField(
            model_name='templates',
            name='other_iban',
            field=models.CharField(max_length=34),
        ),
    ]
